# Change these first
owner: mertmr # Your GitHub organization or username, where this repository lives
repo: upptime-pirot # The name of this repository

sites:
  - name: Pirot
    url: https://pirot.io/management/health
assignees: # Users to assign downtime issues (optional)
  - mertmr

status-website:
  baseUrl: /repo # where "repo" is your repository name
  name: Your Status Website
